# Generated by Django 4.2.6 on 2023-10-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_pollserver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='name',
            new_name='parties_name',
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.CharField(choices=[('IND', 'INDIA'), ('AUS', 'AUSTRALIA')], default='IND', max_length=10),
        ),
    ]
