# Generated by Django 4.2.6 on 2023-10-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_pollserver', '0002_rename_name_party_parties_name_alter_state_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='location',
        ),
    ]
