# Generated by Django 4.2.6 on 2023-10-28 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election_pollserver', '0004_rename_first_name_voter_name_remove_voter_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election_pollserver.state'),
        ),
    ]
